<?php

return [
    'enabled' => (bool) env('FACTUS_ENABLED', false),
    'environment' => env('FACTUS_ENVIRONMENT', 'sandbox'),
    'sandbox_base_url' => env('FACTUS_SANDBOX_BASE_URL', 'https://api-sandbox.factus.com.co'),
    'production_base_url' => env('FACTUS_PRODUCTION_BASE_URL', 'https://api.factus.com.co'),
    'client_id' => env('FACTUS_CLIENT_ID'),
    'client_secret' => env('FACTUS_CLIENT_SECRET'),
    'username' => env('FACTUS_USERNAME'),
    'password' => env('FACTUS_PASSWORD'),
    'numbering_range_id' => env('FACTUS_NUMBERING_RANGE_ID'),
    'document_code' => env('FACTUS_DOCUMENT_CODE', '01'),
    'operation_type' => env('FACTUS_OPERATION_TYPE', '10'),
    'send_email' => (bool) env('FACTUS_SEND_EMAIL', true),
    'default_identification_document_code' => env('FACTUS_DEFAULT_IDENTIFICATION_DOCUMENT_CODE', '13'),
    'default_legal_organization_code' => env('FACTUS_DEFAULT_LEGAL_ORGANIZATION_CODE', '2'),
    'default_tribute_code' => env('FACTUS_DEFAULT_TRIBUTE_CODE', 'ZZ'),
    'default_municipality_code' => env('FACTUS_DEFAULT_MUNICIPALITY_CODE'),
    'default_unit_measure_code' => env('FACTUS_DEFAULT_UNIT_MEASURE_CODE', '94'),
    'default_standard_code' => env('FACTUS_DEFAULT_STANDARD_CODE', '999'),
    'timeout' => (int) env('FACTUS_TIMEOUT', 15),
    'connect_timeout' => (int) env('FACTUS_CONNECT_TIMEOUT', 10),
    'token_cache_ttl' => (int) env('FACTUS_TOKEN_CACHE_TTL', 540),
];
